// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb6PuDFbTRhlGNCADxhZ8fHVk_HrvJ9I0',
    appId: '1:183991718878:web:04f382fd6e6b70a2ad834f',
    messagingSenderId: '183991718878',
    projectId: 'photo-library-app-c57a2',
    authDomain: 'photo-library-app-c57a2.firebaseapp.com',
    storageBucket: 'photo-library-app-c57a2.appspot.com',
    measurementId: 'G-B5X1B4EJC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBucNNS34muZq8Ti_5sytDkLAcob3giwRA',
    appId: '1:183991718878:android:02d3490f407fc16fad834f',
    messagingSenderId: '183991718878',
    projectId: 'photo-library-app-c57a2',
    storageBucket: 'photo-library-app-c57a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB5eYCLR7sSENrmD3YbHGMSX0msjv6Mq4',
    appId: '1:183991718878:ios:effa37974cf0f0b2ad834f',
    messagingSenderId: '183991718878',
    projectId: 'photo-library-app-c57a2',
    storageBucket: 'photo-library-app-c57a2.appspot.com',
    iosClientId: '183991718878-9kc1ps64q66q5oejovkbrvrvqnlto5a7.apps.googleusercontent.com',
    iosBundleId: 'com.example.blocFairebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB5eYCLR7sSENrmD3YbHGMSX0msjv6Mq4',
    appId: '1:183991718878:ios:effa37974cf0f0b2ad834f',
    messagingSenderId: '183991718878',
    projectId: 'photo-library-app-c57a2',
    storageBucket: 'photo-library-app-c57a2.appspot.com',
    iosClientId: '183991718878-9kc1ps64q66q5oejovkbrvrvqnlto5a7.apps.googleusercontent.com',
    iosBundleId: 'com.example.blocFairebaseAuth',
  );
}
